# Generated by Django 3.1.4 on 2020-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Изменение списка')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('list_model', models.CharField(max_length=256, verbose_name='Список')),
                ('is_done', models.BooleanField(default=False)),
                ('expare_date', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Необходимо сделать',
                'verbose_name_plural': 'Необходимо сделать',
            },
        ),
    ]
