# Generated by Django 3.1.4 on 2020-12-16 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Список дел', 'verbose_name_plural': 'Список дел'},
        ),
        migrations.AlterUniqueTogether(
            name='list',
            unique_together={('name', 'user')},
        ),
    ]
